### ISSUE TITLE
Does not seem to work with latest release of Redactor

### ISSUE THREAD

**Issue by mark-chief** [pixelandtonic/RedactorClips#13] opened 2018-05-10 08:01 UTC
Fresh install of Craft 3 v3.0.6 and Redactor v2.0.1.

My Standard.json looks like this: 

```
{
  "buttons": ["formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "image", "video","html"],
  "plugins": ["fullscreen", "video", "clips", "table"],
  "toolbarFixed": true
}
```

**Comment by elodiegrondin** [comment] 2018-05-16 10:28
Same issue for me.
Did you find any fix for this ?

**Comment by mark-chief** [comment] 2018-05-16 10:42
@elodiegrondin I uninstalled the plugin in the end and went with the below in my Standard.json file.

The Craft docs say that all first party redactor plugins are bundled with the Craft Redactor Plugin. Just need to ensure commas, and quotes are formatted for Json so sliughtly different from the docs [here](https://imperavi.com/redactor/plugins/clips/)

```
{
  "buttons": ["formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "image", "video", "html"],
  "plugins": ["fullscreen", "video", "clips", "table"],
  "toolbarFixed": true,
  "clips": [
                ["Black Block", "<div class='big-idea bg-black'><h2>A heading here</h2><p>Some text here</p></div>"]            
           ]
}
```

**Comment by elodiegrondin** [comment] 2018-05-16 13:45
@mark-chief You're absolutely right, this solved my problem.
Thanks for your help !

**Comment by bramus** [comment] 2018-05-29 20:45
Same here. The problem is that the clips define via the Craft Plugin Settings are not being taken into account. Only the clips defined in the .json file are.

**Comment by rauwebieten** [comment] 2018-07-19 09:52
As bramus stated, clips only work with a custom config file.
I cannot get the plugin clips (defined in the plugin settings), into the custom json config file.

```json
{
  "buttons": ["html", "format", "bold", "italic", "lists", "link", "file"],
  "plugins": ["clips","fullscreen"],
  "clips": [
    // get clips from plugins settings here ?
    ["Lorem ipsum...", "Lorem..."],
    ["Red label", "<b class='label-red'>Label</b>"]
  ]
}
```

**Comment by brandonkelly** [comment] 2018-07-29 14:05
We’re retiring this plugin, as Redactor 3’s [Clips plugin](https://imperavi.com/redactor/plugins/clips/) allows you to define your clips right in the main Redactor config file.

So just edit your Redactor config JSON file, and add this:

```javascript
{
    "plugins": [
        "clips"
        // , ...
    ],
    "clips": [
        ["Test Paragraph", ",<p>Testing</p>"]
        // , ...
    ]
    // , ...
}
```

**Closed as completed by brandonkelly** 2018-07-29 14:05 UTC
